[{'year': '2023', 'month': '02', 'total_in': 15.5, 'total_out': 5180.3, 'items': [{'item': {'id': 3360,
                                                                                            'avatarurl': '默认头像',
                                                                                            'nickname': '滴滴',
                                                                                            'nickname_time': '2023-02-24 04:46:17',
                                                                                            'price': '5180.30',
                                                                                            'in_out': 0,
                                                                                            'belong': '12345'},
                                                                                   'price': 5180.3}, {
                                                                                      'item': {'id': 3361,
                                                                                               'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                               'nickname': '微信红包-来自忧梦',
                                                                                               'nickname_time': '2023-02-24 04:46:17',
                                                                                               'price': '15.50',
                                                                                               'in_out': 1,
                                                                                               'belong': '12345'},
                                                                                      'price': 15.5}]},
 {'year': '2023', 'month': '01', 'total_in': 17166.56, 'total_out': 6283.030000000001, 'items': [{'item': {'id': 3384,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '洗澡',
                                                                                                           'nickname_time': '2023-01-27 17:57:30',
                                                                                                           'price': '1186.51',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 1186.51}, {
                                                                                                     'item': {
                                                                                                         'id': 3385,
                                                                                                         'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                         'nickname': '微信红包-来自为何要爱丶',
                                                                                                         'nickname_time': '2023-01-27 17:57:30',
                                                                                                         'price': '9680.86',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 9680.86},
                                                                                                 {'item': {'id': 3374,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '字画',
                                                                                                           'nickname_time': '2023-01-25 17:15:36',
                                                                                                           'price': '5096.52',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 5096.52}, {
                                                                                                     'item': {
                                                                                                         'id': 3375,
                                                                                                         'avatarurl': '默认头像',
                                                                                                         'nickname': '转账-来自媚舞々鬼依',
                                                                                                         'nickname_time': '2023-01-25 17:15:36',
                                                                                                         'price': '7485.70',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 7485.7}]},
 {'year': '2022', 'month': '12', 'total_in': 2379.82, 'total_out': 5636.59, 'items': [{'item': {'id': 3362,
                                                                                                'avatarurl': '默认头像',
                                                                                                'nickname': '洗澡',
                                                                                                'nickname_time': '2022-12-31 04:17:47',
                                                                                                'price': '2539.78',
                                                                                                'in_out': 0,
                                                                                                'belong': '12345'},
                                                                                       'price': 2539.78}, {
                                                                                          'item': {'id': 3363,
                                                                                                   'avatarurl': '默认头像',
                                                                                                   'nickname': '转账-来自可爱￥雪琪',
                                                                                                   'nickname_time': '2022-12-31 04:17:47',
                                                                                                   'price': '2205.92',
                                                                                                   'in_out': 1,
                                                                                                   'belong': '12345'},
                                                                                          'price': 2205.92}, {
                                                                                          'item': {'id': 3358,
                                                                                                   'avatarurl': '默认头像',
                                                                                                   'nickname': '足疗',
                                                                                                   'nickname_time': '2022-12-01 11:43:20',
                                                                                                   'price': '3096.81',
                                                                                                   'in_out': 0,
                                                                                                   'belong': '12345'},
                                                                                          'price': 3096.81}, {
                                                                                          'item': {'id': 3359,
                                                                                                   'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                   'nickname': '微信红包-来自忧梦',
                                                                                                   'nickname_time': '2022-12-01 11:43:20',
                                                                                                   'price': '173.90',
                                                                                                   'in_out': 1,
                                                                                                   'belong': '12345'},
                                                                                          'price': 173.9}]},
 {'year': '2022', 'month': '10', 'total_in': 2686.7, 'total_out': 4889.75, 'items': [{'item': {'id': 3366,
                                                                                               'avatarurl': '默认头像',
                                                                                               'nickname': '酒店',
                                                                                               'nickname_time': '2022-10-08 08:12:23',
                                                                                               'price': '4889.75',
                                                                                               'in_out': 0,
                                                                                               'belong': '12345'},
                                                                                      'price': 4889.75}, {
                                                                                         'item': {'id': 3367,
                                                                                                  'avatarurl': '默认头像',
                                                                                                  'nickname': '转账-来自完美邂逅',
                                                                                                  'nickname_time': '2022-10-08 08:12:23',
                                                                                                  'price': '2686.70',
                                                                                                  'in_out': 1,
                                                                                                  'belong': '12345'},
                                                                                         'price': 2686.7}]},
 {'year': '2022', 'month': '08', 'total_in': 6146.2699999999995, 'total_out': 8100.35, 'items': [{'item': {'id': 3378,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '吃饭',
                                                                                                           'nickname_time': '2022-08-25 02:07:20',
                                                                                                           'price': '6138.79',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 6138.79}, {
                                                                                                     'item': {
                                                                                                         'id': 3379,
                                                                                                         'avatarurl': '默认头像',
                                                                                                         'nickname': '转账-来自ˉ以往的最美',
                                                                                                         'nickname_time': '2022-08-25 02:07:20',
                                                                                                         'price': '5331.98',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 5331.98},
                                                                                                 {'item': {'id': 3380,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '字画',
                                                                                                           'nickname_time': '2022-08-08 06:45:04',
                                                                                                           'price': '1961.56',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 1961.56}, {
                                                                                                     'item': {
                                                                                                         'id': 3381,
                                                                                                         'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                         'nickname': '微信红包-来自离沐倾城',
                                                                                                         'nickname_time': '2022-08-08 06:45:04',
                                                                                                         'price': '814.29',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 814.29}]},
 {'year': '2022', 'month': '07', 'total_in': 17621.66, 'total_out': 20725.72, 'items': [{'item': {'id': 3370,
                                                                                                  'avatarurl': '默认头像',
                                                                                                  'nickname': '吃饭',
                                                                                                  'nickname_time': '2022-07-22 05:45:12',
                                                                                                  'price': '7996.24',
                                                                                                  'in_out': 0,
                                                                                                  'belong': '12345'},
                                                                                         'price': 7996.24}, {
                                                                                            'item': {'id': 3371,
                                                                                                     'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                     'nickname': '微信红包-来自明天见',
                                                                                                     'nickname_time': '2022-07-22 05:45:12',
                                                                                                     'price': '4636.81',
                                                                                                     'in_out': 1,
                                                                                                     'belong': '12345'},
                                                                                            'price': 4636.81}, {
                                                                                            'item': {'id': 3368,
                                                                                                     'avatarurl': '默认头像',
                                                                                                     'nickname': '字画',
                                                                                                     'nickname_time': '2022-07-13 00:56:00',
                                                                                                     'price': '6866.42',
                                                                                                     'in_out': 0,
                                                                                                     'belong': '12345'},
                                                                                            'price': 6866.42}, {
                                                                                            'item': {'id': 3369,
                                                                                                     'avatarurl': '默认头像',
                                                                                                     'nickname': '转账-来自迷糊de糖糖',
                                                                                                     'nickname_time': '2022-07-13 00:56:00',
                                                                                                     'price': '6193.88',
                                                                                                     'in_out': 1,
                                                                                                     'belong': '12345'},
                                                                                            'price': 6193.88}, {
                                                                                            'item': {'id': 3382,
                                                                                                     'avatarurl': '默认头像',
                                                                                                     'nickname': '足疗',
                                                                                                     'nickname_time': '2022-07-05 03:22:05',
                                                                                                     'price': '5863.06',
                                                                                                     'in_out': 0,
                                                                                                     'belong': '12345'},
                                                                                            'price': 5863.06}, {
                                                                                            'item': {'id': 3383,
                                                                                                     'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                     'nickname': '微信红包-来自政府小叶',
                                                                                                     'nickname_time': '2022-07-05 03:22:05',
                                                                                                     'price': '6790.97',
                                                                                                     'in_out': 1,
                                                                                                     'belong': '12345'},
                                                                                            'price': 6790.97}]},
 {'year': '2022', 'month': '05', 'total_in': 780.43, 'total_out': 3410.8, 'items': [{'item': {'id': 3376,
                                                                                              'avatarurl': '默认头像',
                                                                                              'nickname': '酒店',
                                                                                              'nickname_time': '2022-05-02 01:16:13',
                                                                                              'price': '3410.80',
                                                                                              'in_out': 0,
                                                                                              'belong': '12345'},
                                                                                     'price': 3410.8}, {
                                                                                        'item': {'id': 3377,
                                                                                                 'avatarurl': '默认头像',
                                                                                                 'nickname': '转账-来自嫣然一笑搏君赞',
                                                                                                 'nickname_time': '2022-05-02 01:16:13',
                                                                                                 'price': '780.43',
                                                                                                 'in_out': 1,
                                                                                                 'belong': '12345'},
                                                                                        'price': 780.43}]},
 {'year': '2022', 'month': '04', 'total_in': 15976.210000000001, 'total_out': 9334.89, 'items': [{'item': {'id': 3372,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '吃饭',
                                                                                                           'nickname_time': '2022-04-23 14:31:00',
                                                                                                           'price': '7249.41',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 7249.41}, {
                                                                                                     'item': {
                                                                                                         'id': 3373,
                                                                                                         'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                         'nickname': '微信红包-来自莫筱夜',
                                                                                                         'nickname_time': '2022-04-23 14:31:00',
                                                                                                         'price': '6795.02',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 6795.02},
                                                                                                 {'item': {'id': 3364,
                                                                                                           'avatarurl': '默认头像',
                                                                                                           'nickname': '吃饭',
                                                                                                           'nickname_time': '2022-04-01 13:49:38',
                                                                                                           'price': '2085.48',
                                                                                                           'in_out': 0,
                                                                                                           'belong': '12345'},
                                                                                                  'price': 2085.48}, {
                                                                                                     'item': {
                                                                                                         'id': 3365,
                                                                                                         'avatarurl': '/static/tx/IMG_0004.JPG',
                                                                                                         'nickname': '微信红包-来自哈萨克两个',
                                                                                                         'nickname_time': '2022-04-01 13:49:38',
                                                                                                         'price': '9181.19',
                                                                                                         'in_out': 1,
                                                                                                         'belong': '12345'},
                                                                                                     'price': 9181.19}]}]
